id: P85189B66
initial_creation_type: ocr
source_metadata:
  volumes:
    fc04ec7499cc4332b977d78656d51681:
      base_file: v083.txt
      image_group_id: I1PD95928
      title: འཕགས་པ་ཆོས་ཀྱི་དབྱིངས་ཀྱི་སྙིང་པོའི་རྣམ་པར་འགྲེལ་པ།
      total_pages: 1296
      volume_number: 83
